CREATE TABLE OUT_TRAY
	(
	SENT TIMESTAMP,
	DESTINATION CHAR(8),
	SUBJECT CHAR(64) NOT NULL CONSTRAINT OUT_TRAY_PK PRIMARY KEY,
	NOTE_TEXT VARCHAR(3000) 
   );
CREATE TABLE SCHED 
	(
	CLASS_CODE varchar2(7) NOT NULL, 
	DAY number(10) NOT NULL, 
	STARTING TIMESTAMP, 
	ENDING TIMESTAMP,
	PRIMARY KEY (CLASS_CODE, DAY)
	);
    CREATE TABLE EMP1 
	(
	EMPNO CHAR(6) NOT NULL CONSTRAINT EMP_PK PRIMARY KEY,
	FIRSTNME CHAR(12) NOT NULL,
	MIDINIT vARCHAR(12) NOT NULL,
	LASTNAME VARCHAR(15) NOT NULL,
	SALARY DECIMAL(9,2) CONSTRAINT SAL_CK CHECK (SALARY >= 10000),
	BONUS DECIMAL(9,2), 
	TAX DECIMAL(9,2),
	CONSTRAINT BONUS_CK CHECK (BONUS > TAX)
	);
    
    CREATE TABLE FLIGHTS
	(
	FLIGHT_ID varchar(6) NOT NULL ,
	SEGMENT_NUMBER number(10) NOT NULL ,
	ORIG_AIRPORT varchar(3),
	DEPART_TIME TIMESTAMP,
	DEST_AIRPORT varchar(3),
	ARRIVE_TIME TIMESTAMP,
	MEAL varchar(1) CONSTRAINT MEAL_CONSTRAINT 
	CHECK (MEAL IN ('B', 'L', 'D', 'S')),
	PRIMARY KEY (FLIGHT_ID, SEGMENT_NUMBER)
	);
CREATE TABLE METROPOLITAN1
	(
	HOTEL_ID INT NOT NULL CONSTRAINT HOTELS_PK PRIMARY KEY,
	HOTEL_NAME VARCHAR(40) NOT NULL,
	CITY_ID INT CONSTRAINT METRO_FK REFERENCES CITIES
	);

CREATE TABLE FLTAVAIL
(
    FLIGHT_ID CHAR(6) NOT NULL, 
    SEGMENT_NUMBER NUMBER(10) NOT NULL, -- Change to NUMBER(10)
    FLIGHT_DATE DATE NOT NULL, 
    ECONOMY_SEATS_TAKEN INT,
    BUSINESS_SEATS_TAKEN INT,
    FIRSTCLASS_SEATS_TAKEN INT, 
    PRIMARY KEY (FLIGHT_ID, SEGMENT_NUMBER), 
    
    FOREIGN KEY (FLIGHT_ID, SEGMENT_NUMBER)
    REFERENCES Flights (FLIGHT_ID, SEGMENT_NUMBER)
);



